name: GlitzoriumSMP
version: '1.0-SNAPSHOT'
main: de.construkter.glitzoriumSMP.GlitzoriumSMP
api-version: '1.21'

commands:
  hub:
    description: Gehe in die Lobby
  lobby:
    description: Gehe in die Lobby
  playeradd:
    description: Füge einen Spieler zur Whitelist hinzu
  playerremove:
    description: Lösche einen Spieler von der Whitelist
  prepare:
    description: Bereite den Start vor
  start-confirm:
    description: Geheim
  start:
    description: Auch geheim
