name: GlitzoriumSMP
version: '1.0-SNAPSHOT'
main: de.construkter.glitzoriumSMP.GlitzoriumSMP
api-version: '1.21'

commands:
  hub:
    description: Gehe in die Lobby
  lobby:
    description: Gehe in die Lobby
  playeradd:
    description: Füge einen Spieler zur Whitelist hinzu
  playerremove:
    description: Lösche einen Spieler von der Whitelist
  sun:
    description: Wechsle zu schönem Wetter
  day:
    description: Lasse die Sonne aufgehen
  night:
    description: Lasse die Sonne untergehen
  gm:
    description: Wechsle den Gamemode
  chat:
    description: Erlaubt Bedrock Spielern in den Chat ohne Chat Signing zu schreiben
  warn:
    description: Warnt einen Spieler
  kick:
    description: Kickt einen Spieler
  ban:
    description: Bannt einen Spieler
  mute:
    description: Schaltet einen Spieler stumm
  unmute:
    description: Entstummt einen Spieler
  status:
    description: Setze einen Status wie in CraftAttack